repos:
  # Run Black - the uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace
      # Check validity of JSON files
      - id: check-json
      # Format JSON files consistently
      - id: pretty-format-json
        args:
          - --autofix
